-- CreateTable
CREATE TABLE "IgdbGames" (
    "igdbId" INTEGER NOT NULL,
    "checksum" TEXT,
    "name" TEXT NOT NULL,
    "slug" TEXT,
    "summary" TEXT,
    "storyline" TEXT,
    "category" INTEGER,
    "first_release_date" TIMESTAMP(3),
    "rating" DOUBLE PRECISION,
    "rating_count" INTEGER,
    "aggregated_rating" DOUBLE PRECISION,
    "aggregated_rating_count" INTEGER,
    "status" INTEGER,
    "version_parent" INTEGER,
    "version_title" TEXT,
    "platforms" TEXT,
    "platform_versions" TEXT,
    "cover" INTEGER,
    "screenshots" TEXT,
    "artworks" TEXT,
    "videos" TEXT,
    "involved_companies" TEXT,
    "collections" TEXT,
    "franchises" TEXT,
    "series" TEXT,
    "game_modes" TEXT,
    "genres" TEXT,
    "themes" TEXT,
    "keywords" TEXT,
    "game_engines" TEXT,
    "multiplayer_modes" TEXT,
    "release_dates" TEXT,
    "external_games" TEXT,
    "websites" TEXT,
    "age_ratings" TEXT,
    "similar_games" TEXT,
    "dlcs" TEXT,
    "expansions" TEXT,
    "standalone_expansions" TEXT,
    "remasters" TEXT,
    "remakes" TEXT,
    "expanded_games" TEXT,
    "ports" TEXT,
    "forks" TEXT,
    "created_at" TIMESTAMP(3),
    "updated_at" TIMESTAMP(3),
    "lastSynced" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "localCreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "localUpdatedAt" TIMESTAMP(3) NOT NULL,
    "syncedForPlatformId" INTEGER,
    "syncedForIgdbPlatformId" INTEGER,
    "syncedForIgdbPlatformVersionId" INTEGER,

    CONSTRAINT "IgdbGames_pkey" PRIMARY KEY ("igdbId")
);
